logging:
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.minseokism: DEBUG
    
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bbs?useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: bbsadmin
    password: A4568520)
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none    
  jpa:
   show-sql: false
   hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
   properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
   devtools:
      liverelaod:
        enabled: true
   freemarker:
      cache: false
