logging:
  file: logs/test.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.minseokism: DEBUG
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbsdb?useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: minseokism
    password: A456852)
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none    
  jpa:
   show-sql: false
   hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
   properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      

    
      