-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- USER Table Create SQL
CREATE TABLE USER
(
	`ID`     VARCHAR(100)    NOT NULL     COMMENT '아이디',
	`PWD`    VARCHAR(100)    NOT NULL     COMMENT '비밀번호',
	`EMAIL`  VARCHAR(100)    NOT NULL     COMMENT '이메일',
	`NAME`   VARCHAR(50)     NOT NULL     COMMENT '이름',
	`TOKEN`  VARCHAR(100)    NULL         COMMENT '토큰',
	PRIMARY KEY (ID)
);

ALTER TABLE USER COMMENT '사용자';


-- POST Table Create SQL
CREATE TABLE POST
(
	`POST_NO`   INTEGER         NOT NULL    AUTO_INCREMENT COMMENT '게시글번호',
	`CATEGORY`  INTEGER         NOT NULL     COMMENT '카테고리',
	`SUBJECT`   VARCHAR(300)    NOT NULL     COMMENT '제목',
	`CONTENT`   TEXT            NOT NULL     COMMENT '내용',
	`REG_DATE`  DATETIME        NOT NULL     COMMENT '등록일자',
	`MOD_DATE`  DATETIME 				DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL     COMMENT '수정일자',
	`HITS`      INTEGER         NULL     		 COMMENT '조회수',
	`ID`        VARCHAR(100)    NOT NULL     COMMENT '아이디',
	`BOARD_NO`  INTEGER         NOT NULL     COMMENT '게시판번호',
	PRIMARY KEY (POST_NO)
);

ALTER TABLE POST COMMENT '게시글';

ALTER TABLE POST ADD CONSTRAINT FK_POST_ID_USER_ID FOREIGN KEY (ID)
REFERENCES USER (ID)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- BOARD Table Create SQL
CREATE TABLE BOARD
(
	`BOARD_NO`  INTEGER        NOT NULL    AUTO_INCREMENT COMMENT '게시판번호',
	`BOARD_NM`  VARCHAR(45)    NOT NULL     COMMENT '게시판이름',
	PRIMARY KEY (BOARD_NO)
);

ALTER TABLE BOARD COMMENT '게시판';


-- COMMENT Table Create SQL
CREATE TABLE COMMENT
(
	`COMMENT_NO`  INTEGER         NOT NULL     AUTO_INCREMENT COMMENT '댓글번호',
	`CONTENT`     TEXT            NOT NULL     COMMENT '내용',
	`REG_DATE`    DATETIME        NOT NULL     COMMENT '등록일자',
	`MOD_DATE`    DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL     COMMENT '수정일자',
	`ID`          VARCHAR(100)    NOT NULL     COMMENT '아이디',
	`POST_NO`     INTEGER         NOT NULL     COMMENT '게시글번호',
	PRIMARY KEY (COMMENT_NO)
);

ALTER TABLE COMMENT COMMENT '댓글';


-- IMAGE Table Create SQL
CREATE TABLE IMAGE
(
	`IMG_NO`   INTEGER          NOT NULL     AUTO_INCREMENT COMMENT '이미지번호',
	`IMG_ADD`  VARCHAR(1000)    NOT NULL     COMMENT '이미지주소',
	`POST_NO`  INTEGER          NOT NULL     COMMENT '게시글번호',
	PRIMARY KEY (IMG_NO)
);

ALTER TABLE IMAGE COMMENT '이미지';


